version: '3.8'

services:
  frontend:
    container_name: mls_frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
      # dockerfile: ./Dockerfile.product
    ports:
      - 3000:3000
    # volumes for dev
    volumes:
      - ./frontend:/usr/app
    env_file:
      - ./frontend/.env
    networks:
      - mls
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    container_name: mls_backend
    build: ./backend
    image: directus/directus:10.9.2
    ports:
      - 8055:8055
    volumes:
      - ./backend/uploads:/directus/uploads
      - ./backend/extensions:/directus/extensions
    env_file:
      - ./backend/.env
    networks:
      - mls
    depends_on:
      - database
    restart: unless-stopped
  
  database:
    container_name: mls_database
    image: bitnami/mysql:8.0
    volumes:
      - ./backend/database:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "mlsvc"
      MYSQL_PASSWORD: "mlsvc"
      MYSQL_DATABASE: "mlsvc"
      MYSQL_AUTHENTICATION_PLUGIN: "mysql_native_password"
    networks:
      - mls
    restart: always

networks:
  mls:

volumes:
  mysql_data:
